version: '3'

services:
    mysql:
        build:
            context: ./infra/docker/mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS:-secret}
            MYSQL_DATABASE: ${DB_NAME:-wordpress}
            MYSQL_USER: ${DB_USER:-phper}
            MYSQL_PASSWORD: ${DB_PASS:-secret}

    wordpress:
        image: wordpress:php7.4-apache
        depends_on:
            - mysql
        ports:
            - ${WEB_PORT:-80}:80
        volumes:
            - ./public:/var/www/html
            - ./infra/docker/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: ${DB_USER:-phper}
            WORDPRESS_DB_PASSWORD: ${DB_PASS:-secret}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=${DB_USER:-phper}
            - PMA_PASSWORD=${DB_PASS:-secret}
        links:
            - mysql
        ports:
            - ${PHPMYADMIN_PORT:-1080}:80
volumes:
    db_data: